name: Snyk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  analyze:
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Create venv
        run: uv venv
      - name: Install dependencies
        run: uv pip install -U -r pyproject.toml --all-extras
      - name: Generate requirements.txt
        run: uv pip freeze > requirements.txt
      - name: Check for High Severity OSS Vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --fail-on=upgradable
